### ISSUE TITLE
Read Me Missing Link to Component JS

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-video#40]
Reproduction Steps
Go to readme under usage of this repo.
There is an undocumented step a designer needs to follow to get the component to work.
Specifically there is no mention of linking to `<script src="https://widgets.risevision.com/stable/components/rise-video/1/rise-video.js"></script>` in the head of your HTML.

Expected Results
I would expect anything that a designer needs to do to get a video component running in their template project should be documented under usage. One of the designers had problems with video component not showing up due to this.

**Comment by stulees** [comment]
Fixed with #41
